# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0059237a92890570dd92683b7fda0feac6461bde5e8911c6a438e685b5737a1a5b3aac838db7e1f55d9982382a8ace4c1f7a71e116594cd75a359d535734a8a5

test:
  secret_key_base: c8ff8e14dbaaf727f8dcc9a09d674b327175e555b26d15ae8ca53fa70b26d1ee3ceee673b985478ea4b827c7bc29be94aa89503c943cdfac2e44ea427ea5d44d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
